name: Storybook Publish

on: push

env:
  NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com/"
      - name: Install dependencies
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
