name: Comment package info to PR
description: Create or update Github PR comment with the package info
author: Vaultinum
runs:
  using: composite
  steps:
    - name: Find package info comment
      uses: peter-evans/find-comment@v1
      id: find-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: github-actions[bot]      
        body-includes: |
          ```
    - name: Get package info
      id: package
      uses: codex-team/action-nodejs-package-info@v1
    - name: Create or update package info comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ```
          npm i ${{ steps.package.outputs.name }}@${{ steps.package.outputs.version }}
        edit-mode: replace