name: Deploy functions
author: Vaultinum
inputs:
  FUNCTIONS_ENVIRONMENT:
    type: string
  FIREBASE_TOKEN:
    type: string
  NPM_PACKAGE_ACCESS:
    type: string

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: latest
    - uses: actions/download-artifact@v4
      with:
        name: functions-build-output
        path: functions/lib
    - name: Replace token
      shell: bash
      run: sed -i "s/\${NPM_PACKAGE_ACCESS}/${{ inputs.NPM_PACKAGE_ACCESS }}/g" functions/.npmrc # replace token
    - name: Install Dependencies
      shell: bash
      run: npm --prefix functions ci
    - name: Deploy functions to Firebase
      uses: w9jds/firebase-action@v13.7.3
      with:
        args: deploy -P ${{ inputs.FUNCTIONS_ENVIRONMENT }} --only functions
      env:
        FIREBASE_TOKEN: ${{ inputs.FIREBASE_TOKEN }}
