name: Execute E2E tests
description: Run E2E tests for applications
author: Vaultinum
inputs:
  e2e_access_token:
    description: Access token for e2e tests
    required: true
  e2e_branch_name:
    description: The e2e branch name as references
    required: true
  application:
    description: Application for which e2e tests will be run
    required: false
    default: ${{ github.event.repository.name }}

runs:
  using: composite
  steps:
    - name: Extract branch name to determine environment
      id: branch_name
      shell: bash
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
    - name: Dispatches end to end test
      shell: bash
      run: |
        curl -X POST https://api.github.com/repos/vaultinum/vaultinum-e2e/actions/workflows/tests.yml/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token ${{ inputs.e2e_access_token }}' \
        --data '{"ref":"${{ inputs.e2e_branch_name }}","inputs":{"application": "${{ inputs.application }}", "branch_refs" : "${{ steps.branch_name.outputs.short_ref }}"}}'