name: Execute E2E tests
description: Run E2E tests of application using this action
author: Vaultinum
inputs:
  e2e_access_token:
    description: Access token for e2e tests
    required: true
  target_api:
    description: Target API for the e2e tests
    required: true
  data:
    description: Data to pass to the e2e tests API
    required: true

runs:
  using: composite
  steps:
    - name: Dispatches end to end test
      shell: bash
      run: |
        curl -X POST ${{ inputs.target_api }} \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token ${{ inputs.e2e_access_token }}' \
        --data '${{ inputs.data }}'
