name: Execute E2E tests
description: Run E2E tests of application using this action
author: Vaultinum
inputs:
  e2e_access_token:
    description: Access token for e2e tests
    required: true
  e2e_branch_name:
    description: The e2e branch name as reference
    default: main
  target_branch:
    description: Target branch for the e2e tests
    default: develop

runs:
  using: composite
  steps:
    - name: Dispatches end to end test
      shell: bash
      run: |
        curl -X POST https://api.github.com/repos/vaultinum/vaultinum-e2e/actions/workflows/tests.yml/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Authorization: token ${{ inputs.e2e_access_token }}' \
        --data '{"ref":"${{ inputs.e2e_branch_name }}","inputs":{"application": "${{ github.event.repository.name }}", "branch_refs" : "${{ inputs.target_branch }}"}}'