name: CI
description: Run install dependencies, build, eslint, tests, generate docs
author: Vaultinum
inputs:
  run_npm_install:
    default: false
    type: boolean
  run_eslint:
    default: true
    type: boolean
  run_build:
    default: true
    type: boolean
  run_build_runtime:
    type: string
    description: "The runtime to use for the build. Can be 'node' or 'bun'. Default is 'node'."
    default: "node"
  run_tests:
    default: false
    type: boolean
  brand:
    type: string
    description: Brand to use for the package
  working-directory:
    type: string
    description: "The working directory for the job"
    default: "."

runs:
  using: composite
  steps:
    - uses: vaultinum/actions/ci-node@39
      if: ${{ inputs.run_build_runtime == 'node' }}
      with:
        run_npm_install: ${{ inputs.run_npm_install }}
        run_eslint: ${{ inputs.run_eslint }}
        run_build: ${{ inputs.run_build }}
        run_tests: ${{ inputs.run_tests }}
        brand: ${{ inputs.brand }}
        working-directory: ${{ inputs.working-directory }}
    - uses: vaultinum/actions/ci-bun@39
      if: ${{ inputs.run_build_runtime == 'bun' }}
      with:
        run_npm_install: ${{ inputs.run_npm_install }}
        run_eslint: ${{ inputs.run_eslint }}
        run_build: ${{ inputs.run_build }}
        run_tests: ${{ inputs.run_tests }}
        brand: ${{ inputs.brand }}
        working-directory: ${{ inputs.working-directory }}
