name: Generate changelog

on:
  workflow_call:
    secrets:
      npm_package_access:
        required: true

jobs:
  changelog:
    # Only if the PR develop -> staging is in review
    if: github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.npm_package_access }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Generate changelog
        run: npm run release
      - name: Commit and push tag
        run: git push --follow-tags origin ${{ github.event.pull_request.head.ref }}
