name: Storybook Publish

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      chromatic_project_token:
        required: true
      npm_package_access:
        required: true

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.npm_package_access }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com/"
      - name: Install dependencies
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.gh_token }}
          projectToken: ${{ secrets.chromatic_project_token }}
