name: Storybook Publish

on:
    workflow_call:
        secrets:
            GH_TOKEN:
                required: true
            CHROMATIC_PROJECT_TOKEN:
                required: true
            NPM_PACKAGE_ACCESS:
                required: true

concurrency:
  group: chromatic-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
          changes_detected: ${{ steps.changes_detected.outputs.changes_detected }}
        steps:
          - id: changes_detected
            uses: vaultinum/actions/check-changes@v19
            with:
                pattern: ^src/|^\.storybook/
    chromatic-deployment:
        needs: check-changes
        if: needs.check-changes.outputs.changes_detected == 'true'
        runs-on: ubuntu-latest
        env:
            NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
            NODE_OPTIONS: --max-old-space-size=8192
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.4.1
                  registry-url: "https://npm.pkg.github.com/"
            - name: Install dependencies
              run: npm i
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  onlyChanged: true
