name: Execute E2E tests

on:
  workflow_call:
    inputs:
      sleep:
        type: boolean
        description: Sleep for 5 minutes
        default: false
      application:
        type: string
        description: The application to test
        required: false
      url:
        type: string
        description: The url to test
        required: false
    secrets:
      e2e_access_token:
        description: Access token for e2e tests
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Dispatches end to end test
        shell: bash
        run: |
          curl -X POST https://api.github.com/repos/vaultinum/vaultinum-e2e/actions/workflows/tests.yml/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Authorization: token ${{ secrets.e2e_access_token }}' \
          --data '{ "ref": "main", "inputs":{ "sleep": "${{ inputs.sleep }}", "application": "${{ inputs.application }}", "url": "${{ inputs.url }}" }}'
