name: Labeler

on:
  workflow_call:
    secrets: 
      GH_TOKEN:
        required: true

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '30'
          m_label: 'size/M'
          m_max_size: '100'
          l_label: 'size/L'
          l_max_size: '500'
          xl_label: 'size/XL'
          xl_max_size: '1000'
          xxl_label: 'size/XXL'
          fail_if_xxl: 'false'
          files_to_ignore: 'package-lock.json *.lock'