name: Merge develop into staging

on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  merge-develop:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Merge develop -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "Merge develop into staging"
          from_branch: develop
          target_branch: staging
          github_token: ${{ secrets.gh_token }}
