name: Setup Node and publish snapshot

on:
  workflow_call:
    secrets:
      npm_package_access:
        required: true
      gh_token:
        required: true

jobs:
  publish_snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.npm_package_access }}
      NODE_AUTH_TOKEN: ${{ secrets.gh_token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com/"
      - name: Install dependencies
        run: npm ci
      - name: Get current date
        run: echo "snapshot_date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Update snapshot version
        run: npm version prerelease --no-git-tag-version --preid=$PRE_ID
        env:
          PRE_ID: SNAPSHOT-${{ env.snapshot_date }}
      - name: Publish snapshot
        run: npm publish --tag=snapshot
      - name: Find package info comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: |
            ```
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1
      - name: Create or update package info comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            npm i ${{ steps.package.outputs.name }}@${{ steps.package.outputs.version }}
          edit-mode: replace
