name: Setup Node and publish snapshot

on:
  workflow_call:
    inputs:
      run_npm_install:
        default: false
        type: boolean
      run_eslint:
        default: true
        type: boolean
      run_build:
        default: true
        type: boolean
      run_tests:
        default: false
        type: boolean
    secrets:
      NPM_PACKAGE_ACCESS:
        required: true
      GH_TOKEN:
        required: true
      SONAR_TOKEN:
        required: false
      SONAR_URL:
        required: false
      TEST_KEY:
        required: false

concurrency:
  group: publish-snapshot-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      TEST_KEY: ${{ secrets.TEST_KEY }}
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com/"
      - name: Trigger ci
        uses: vaultinum/actions/ci@v2
        with:
          run_npm_install: ${{ inputs.run_npm_install }}
          run_eslint: ${{ inputs.run_eslint }}
          run_build: ${{ inputs.run_build }}
          run_tests: ${{ inputs.run_tests }}
      - name: Get current date
        run: echo "snapshot_date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Update snapshot version
        run: npm version prerelease --no-git-tag-version --preid=$PRE_ID
        env:
          PRE_ID: SNAPSHOT-${{ env.snapshot_date }}
      - name: Publish snapshot
        run: npm publish --tag=snapshot
      - name: Find package info comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: |
            ```
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1
      - name: Create or update package info comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            npm i ${{ steps.package.outputs.name }}@${{ steps.package.outputs.version }}
          edit-mode: replace
  sonarqube:
    uses: ./.github/workflows/sonarqube.yaml
    secrets: inherit
  labeler:
    uses: ./.github/workflows/labeler.yaml
    secrets: inherit
