name: Release

on:
    workflow_call:
        inputs:
            run_npm_install:
                default: false
                type: boolean
            run_eslint:
                default: true
                type: boolean
            run_build:
                default: true
                type: boolean
            run_tests:
                default: false
                type: boolean
            publish_package:
                default: true
                type: boolean
            runs-on:
                default: ubuntu-latest
                type: string
            timeout-minutes:
                default: 20
                type: number
            brand:
                type: string
                description: Brand to use for the package
            working-directory:
                type: string
                description: "The working directory for the job"
                default: "."
        outputs:
            version:
                description: Version of the package
                value: ${{ jobs.release.outputs.version }}
        secrets:
            NPM_PACKAGE_ACCESS:
                required: true
            GH_TOKEN:
                required: true
            SONAR_TOKEN:
                required: false
            SONAR_URL:
                required: false
            TEST_KEY:
                required: false
            # Additional optional secrets that can be passed from calling workflow
            LIBRARIES_IO_API_KEY:
                required: false
            SONATYPE_USER:
                required: false
            SONATYPE_PASSWORD:
                required: false

concurrency:
    group: release-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}${{ inputs.brand }}
    cancel-in-progress: true

jobs:
    release:
        runs-on: ${{ inputs.runs-on }}
        outputs:
            version: ${{ steps.package.outputs.version }}
        timeout-minutes: ${{ inputs.timeout-minutes }}
        env:
            NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TEST_KEY: ${{ secrets.TEST_KEY }}
            # Optional secrets - only set if provided
            LIBRARIES_IO_API_KEY: ${{ secrets.LIBRARIES_IO_API_KEY }}
            SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
            SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        steps:
            - name: Checkout Current Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: main
            - name: Setup Git User
              uses: fregante/setup-git-user@v1
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.4.1
                  registry-url: "https://npm.pkg.github.com/"
            - name: Trigger ci
              uses: vaultinum/actions/ci@v28
              with:
                  run_npm_install: ${{ inputs.run_npm_install }}
                  run_eslint: ${{ inputs.run_eslint }}
                  run_build: ${{ inputs.run_build }}
                  run_tests: ${{ inputs.run_tests }}
                  brand: ${{ inputs.brand }}
                  working-directory: ${{ inputs.working-directory }}
            - name: Generate changelog
              working-directory: ${{ inputs.working-directory }}
              run: npm run release
            - name: Commit and push tag
              if: ${{ inputs.brand == '' || inputs.brand == 'vaultinum' }}
              working-directory: ${{ inputs.working-directory }}
              run: git push --follow-tags origin main
            - name: Edit version
              if: ${{ inputs.brand != '' }}
              working-directory: ${{ inputs.working-directory }}
              run: |
                  BRAND="${{ inputs.brand }}"
                  sed -E -i "s/\"version\": \"([0-9]+\.[0-9]+\.[0-9]+)\"/\"version\": \"\1-$BRAND\"/g" package.json
            - name: Publish
              working-directory: ${{ inputs.working-directory }}
              if: ${{ inputs.publish_package == true }}
              run: npm publish
            - name: Get package info
              id: package
              uses: codex-team/action-nodejs-package-info@v1.1
              with:
                  path: ${{ inputs.working-directory }}
    sonarqube:
        if: ${{ inputs.run_tests != true && (inputs.brand == '' || inputs.brand == 'vaultinum') }}
        uses: ./.github/workflows/sonarqube.yaml
        secrets: inherit
        with:
            working-directory: ${{ inputs.working-directory }}
    sonarqube-with-coverage:
        if: ${{ inputs.run_tests == true && (inputs.brand == '' || inputs.brand == 'vaultinum') }}
        needs: release
        uses: ./.github/workflows/sonarqube.yaml
        secrets: inherit
        with:
            run_tests: ${{ inputs.run_tests }}
            brand: ${{ inputs.brand }}
            working-directory: ${{ inputs.working-directory }}
