name: Release

on:
  workflow_call:
    inputs:
      run_npm_install:
        default: false
        type: boolean
      run_eslint:
        default: true
        type: boolean
      run_build:
        default: true
        type: boolean
      run_tests:
        default: false
        type: boolean
      generate_docs:
        default: false
        type: boolean
      publish_package:
        default: true
        type: boolean
    secrets:
      NPM_PACKAGE_ACCESS:
        required: true
      GH_TOKEN:
        required: true
      SONAR_TOKEN:
        required: false
      SONAR_URL:
        required: false
      TEST_KEY:
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TEST_KEY: ${{ secrets.TEST_KEY }}
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Setup Git User
        uses: fregante/setup-git-user@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com/"
      - name: Trigger ci
        uses: vaultinum/actions/ci@v2
        with:
          run_npm_install: ${{ inputs.run_npm_install }}
          run_eslint: ${{ inputs.run_eslint }}
          run_build: ${{ inputs.run_build }}
          run_tests: ${{ inputs.run_tests }}
          generate_docs: ${{ inputs.generate_docs }}
      - name: Generate changelog
        run: npm run release
      - name: Commit and push tag
        run: git push --follow-tags origin main
      - name: Publish
        if: ${{ inputs.publish_package == true }}
        run: npm publish
  sonarqube:
    uses: ./.github/workflows/sonarqube.yaml
    secrets: inherit
