name: Release

on:
  workflow_call:
    inputs:
      publish_package:
        default: true
        type: boolean
    secrets:
      npm_package_access:
        required: true
      gh_token:
        required: true
      sonar_url:
        required: true
      sonar_token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.npm_package_access }}
      NODE_AUTH_TOKEN: ${{ secrets.gh_token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com/"
      - name: Install dependencies
        run: npm ci
      - name: Generate changelog
        run: npm run release
      - name: Commit and push tag
        run: git push --follow-tags origin main
      - name: Publish
        if: inputs.publish_package == true
        run: npm publish
  sonarqube:
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      sonar_token: ${{ secrets.sonar_token }}
      sonar_url: ${{ secrets.sonar_url }}
