name: SonarQube

on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use for the job"
        type: string
        default: "self-hosted"
      run_tests:
        default: false
        type: boolean
      brand:
        type: string
        description: Brand to use for the package
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_URL:
        required: true

concurrency:
  group: sonarqube-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sonarQube:
    name: SonarQube analysis
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download code coverage results
        if: ${{ inputs.run_tests == true }}
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report-${{ inputs.brand }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.javascript.lcov.reportPaths=./lcov.info
            -Dsonar.dependencyCheck.jsonReportPath=${{ github.workspace }}/dependency-check-report.json
            -Dsonar.dependencyCheck.htmlReportPath=${{ github.workspace }}/dependency-check-report.html
