name: E2E tests

on:
  workflow_call:
    inputs:
      target_api:
        required: true
      data:
        required: true
    secrets:
      e2e_access_token:
        required: true

tests:
  runs-on: self-hosted
  timeout-minutes: 30
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Trigger e2e tests
      uses: ./.github/workflows/e2e-tests
      with:
        e2e_access_token: ${{ secrets.e2e_access_token }}
        target_api: ${{ inputs.target_api }}
        data: ${{ inputs.data }}
