name: Unit test

on:
  workflow_call:
    secrets:
      NPM_PACKAGE_ACCESS:
        required: true
      STRIPE_TEST_TOKEN:
        required: true

concurrency:
  group: unit-test-functions-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-api:
    name: Tests api
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
      STRIPE_TEST_TOKEN: ${{ secrets.STRIPE_TEST_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Change npm cache directory
        run: npm config set cache . --global
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm --prefix functions ci --cache ./.npm --prefer-offline
      - name: Tests api
        run: npm --prefix functions run test:emulator:api
  tests-common:
    name: Tests common
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
      STRIPE_TEST_TOKEN: ${{ secrets.STRIPE_TEST_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ env.cache-name }}-
            build-
      - name: Install dependencies
        run: npm --prefix functions ci --cache ./.npm --prefer-offline
      - name: Tests common
        run: npm --prefix functions run test:emulator:common
  tests-services:
    name: Tests services
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NPM_PACKAGE_ACCESS: ${{ secrets.NPM_PACKAGE_ACCESS }}
      STRIPE_TEST_TOKEN: ${{ secrets.STRIPE_TEST_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./.npm
          key: build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ env.cache-name }}-
            build-
      - name: Install dependencies
        run: npm --prefix functions ci --cache ./.npm --prefer-offline
      - name: Tests services
        run: npm --prefix functions run test:emulator:services